### ISSUE TITLE
vertex_buffer.lockAll() , bug?

### ISSUE THREAD

**Issue by rayloi777** [Apprentice-Alchemist/KincHL#5]
![Texture 3_16_2022 8_56_45 PM](https://user-images.githubusercontent.com/13784700/158596409-30f3e15c-f253-40a9-8a53-f6cf0c226639.png)

and run again again again again can see triangle

![Texture 3_16_2022 8_56_55 PM](https://user-images.githubusercontent.com/13784700/158596461-f54b1cf1-16fc-464b-92a8-54bbd618cc05.png)

**Comment by Apprentice-Alchemist** [comment]
Is this only on D3D11, or also on OpenGL? (`haxe --run Build -g opengl` to rebuild with OpenGL instead of D3D11)
And if I'm understanding this correctly, the bug does not occur consistently?

**Comment by rayloi777** [comment]
I used D3D11 and used krafix.exe compile to .d3d11 shader

**Comment by rayloi777** [comment]
Oh, i know what happened, change var v = vertex_buffer.lock(0, 3); is Working 
Thanks for your help :)
